export interface Strategy {
  id: string;
  name: string;
  creator: string;
  username: string;
  followers: string;
  bio: string;
  avatar: string;
  allocation: Record<string, number>;
  return12mo: number;
  riskLevel: "Low" | "Medium" | "High";
  winRate: number;
  benefits?: string[]; // Add benefits for Neo-specific features
}

export const strategies: Strategy[] = [
  {
    id: "neo-native",
    name: "Neo Native",
    creator: "NeoFoundation",
    username: "@neofoundation",
    followers: "12.4k",
    bio: "Core infrastructure play with GAS generation",
    avatar: "🟢",
    allocation: {
      GAS: 60,
      NEO: 30,
      FLM: 10,
    },
    return12mo: 18,
    riskLevel: "Low",
    winRate: 89,
    benefits: [
      "0.001 GAS transaction fees (vs $2+ on Ethereum)",
      "Native Neo assets - no wrapped tokens",
      "Earn GAS rewards while holding NEO",
    ],
  },
  {
    id: "conservative-stacker",
    name: "Conservative Stacker",
    creator: "SafeInvestor",
    username: "@safeinvestor",
    followers: "8.9k",
    bio: "Pure utility, earn while you hold",
    avatar: "🛡️",
    allocation: {
      GAS: 100,
    },
    return12mo: 12,
    riskLevel: "Low",
    winRate: 92,
    benefits: [
      "Lowest volatility Neo asset",
      "Required for all Neo transactions",
      "Generated by holding NEO",
    ],
  },
  {
    id: "neo-gaming",
    name: "Neo Gaming Exposure",
    creator: "Web3Gamer",
    username: "@web3gamer",
    followers: "15.2k",
    bio: "Gaming + DeFi diversification",
    avatar: "🎮",
    allocation: {
      GAS: 50,
      SOUL: 30,
      NEO: 20,
    },
    return12mo: 24,
    riskLevel: "Medium",
    winRate: 78,
    benefits: [
      "Exposure to Neo's fastest-growing sector",
      "SOUL gaming ecosystem growth",
      "Balanced with stable GAS foundation",
    ],
  },
];

export interface PortfolioData {
  hasStrategy: boolean;
  strategy: {
    id: string;
    name: string;
    creator: string;
    allocation: Record<string, number>;
    weeklyAmount: number;
    weeksCompleted: number;
    totalWeeks: number | null;
    strictMode: boolean;
  } | null;
  portfolio: {
    holdings: Record<string, number>;
    holdingsValue: Record<string, number>;
    holdingsChange: Record<string, number>;
    totalValue: number;
    costBasis: number;
    profitLoss: number;
    profitLossPercent: number;
  };
  nextDCA: string;
  dcaPoolBalance: number;
}

export interface Transaction {
  week: number;
  date: string;
  purchased: Record<string, number>;
  gasSpent: number;
  txHash: string;
}

export const mockPortfolio: PortfolioData = {
  hasStrategy: false,
  strategy: null,
  portfolio: {
    holdings: {},
    holdingsValue: {},
    holdingsChange: {},
    totalValue: 0,
    costBasis: 0,
    profitLoss: 0,
    profitLossPercent: 0,
  },
  nextDCA: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  dcaPoolBalance: 0,
};

export const mockTransactions: Transaction[] = [];

// Neo ecosystem token prices (approximate)
export const cryptoPrices: Record<string, number> = {
  GAS: 3.42, // Neo utility token
  NEO: 15.8, // Neo governance token
  FLM: 0.12, // Flamingo Finance
  SOUL: 0.08, // Phantasma (Neo gaming)
};
